sudo: False

language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test python=$TRAVIS_PYTHON_VERSION pytest heapdict
  - source activate test
  - conda install -c conda-forge python-lmdb

  - python setup.py install

script:
  - py.test --doctest-modules zict

notifications:
  email: false
