name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v1.7.0
        with:
          auto-update-conda: true
          miniconda-version: latest
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Install dependencies
        shell: bash -l {0}
        run: conda install pytest flake8 black heapdict python-lmdb psutil

      - name: Install zict
        shell: bash -l {0}
        run: python setup.py install

      - name: Run flake8
        shell: bash -l {0}
        run: flake8 zict

      - name: Run black
        shell: bash -l {0}
        run: black --check zict

      - name: Run pytest
        shell: bash -l {0}
        run: pytest --doctest-modules zict
