name: Test

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: latest
          activate-environment: test
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: conda install -c conda-forge pytest heapdict python-lmdb psutil

      - name: Install zict
        shell: bash -l {0}
        run: python setup.py install

      - name: Run pytest
        shell: bash -l {0}
        run: pytest --doctest-modules zict
